apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lovetest-admin-ingress
  labels:
    app: lovetest-admin
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - admin.lovetest.com.cn
    secretName: lovetest-admin-tls
  rules:
  - host: admin.lovetest.com.cn
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: lovetest-admin-service
            port:
              number: 80