apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: lovetest-admin

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

commonLabels:
  app: lovetest-admin
  managed-by: argocd

images:
  - name: omaticaya/lovetest-admin
    newTag: latest

namespace: lovetest